# generated by zon2nix (https://github.com/Cloudef/zig2nix)

{
  lib,
  linkFarm,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig,
  name ? "zig-packages",
}:

with builtins;
with lib;

let
  unpackZigArtifact =
    { name, artifact }:
    runCommandLocal name { nativeBuildInputs = [ zig ]; } ''
      hash="$(zig fetch --global-cache-dir "$TMPDIR" ${artifact})"
      mv "$TMPDIR/p/$hash" "$out"
      chmod 755 "$out"
    '';

  fetchZig =
    {
      name,
      url,
      hash,
    }:
    let
      artifact = fetchurl { inherit url hash; };
    in
    unpackZigArtifact { inherit name artifact; };

  fetchGitZig =
    {
      name,
      url,
      hash,
      rev ? throw "rev is required, remove and regenerate the zon2json-lock file",
    }:
    let
      parts = splitString "#" url;
      url_base = elemAt parts 0;
      url_without_query = elemAt (splitString "?" url_base) 0;
    in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
    };

  fetchZigArtifact =
    {
      name,
      url,
      hash,
      ...
    }@args:
    let
      parts = splitString "://" url;
      proto = elemAt parts 0;
      path = elemAt parts 1;
      fetcher = {
        "git+http" = fetchGitZig (
          args
          // {
            url = "http://${path}";
          }
        );
        "git+https" = fetchGitZig (
          args
          // {
            url = "https://${path}";
          }
        );
        http = fetchZig {
          inherit name hash;
          url = "http://${path}";
        };
        https = fetchZig {
          inherit name hash;
          url = "https://${path}";
        };
      };
    in
    fetcher.${proto};
in
linkFarm name [
  {
    name = "sokol-0.1.0-pb1HK1lnLQBiH8mYgOj27tfYcAdUg_zs9GNcfei3hjye";
    path = fetchZigArtifact {
      name = "sokol";
      url = "git+https://github.com/floooh/sokol-zig.git#a489c96608bba84bc9262eebdeec8261e603027c";
      hash = "sha256-sT47qRloSuX5h42c9g8jxYkl+8ChkmqiSFVY6vDaVPM=";
      rev = "a489c96608bba84bc9262eebdeec8261e603027c";
    };
  }
  {
    name = "N-V-__8AAOG3BQCJ9cn-N2swm2o5cLmDhmdHmtwNngOChK78";
    path = fetchZigArtifact {
      name = "emsdk";
      url = "git+https://github.com/emscripten-core/emsdk#4.0.3";
      hash = "sha256-avoxKxJlerL5khjG7veXUJshYl53ELyyb1In3nqcsyk=";
      rev = "127ce42cd5f0aabe2d9b5d636041ccef7c66d165";
    };
  }
  {
    name = "sokolshdc-0.1.0-r2KZDtzckwTGGk0k4xotl5r1-15ary_9-vvFzv5cUxKn";
    path = fetchZigArtifact {
      name = "shdc";
      url = "git+https://github.com/floooh/sokol-tools-bin#90d2b9267813cbfb66e26c8e3eca5cc866f947e0";
      hash = "sha256-x48PGfnRk3GSUUYscCFsR/+yuWBekuymjXugUw5fddc=";
      rev = "90d2b9267813cbfb66e26c8e3eca5cc866f947e0";
    };
  }
  {
    name = "zigimg-0.1.0-meDTrz9eEAA9BebDVEhuvbV1spX1NWa3BxyQrvzxrTXV";
    path = fetchZigArtifact {
      name = "zigimg";
      url = "git+https://github.com/Cethannel/zigimg.git#64705348779b0b24d1f638c857cba42caf592882";
      hash = "sha256-yJhZsFbkqCTR2jLjgdr4N2Ml+D6rVhjVyOb9aI+iA78=";
      rev = "64705348779b0b24d1f638c857cba42caf592882";
    };
  }
  {
    name = "zlm-0.1.0-2FyqUG2lAADCmyNMKbEICc9hdHAM3lOr_qPGmEY12wiA";
    path = fetchZigArtifact {
      name = "zlm";
      url = "git+https://github.com/Cethannel/zlm#340617d6d62088a0f7101fe19a53c73395ee8b0e";
      hash = "sha256-7eBsow1OBV8LeZzNU2P/2Qh1f9j0K5ioXupGaE3ajlY=";
      rev = "340617d6d62088a0f7101fe19a53c73395ee8b0e";
    };
  }
  {
    name = "cimgui-0.1.0-44ClkVShhQApVaApfb_mhXPpp08yqiB3zIBR0WYjbwwI";
    path = fetchZigArtifact {
      name = "cimgui";
      url = "git+https://github.com/floooh/dcimgui.git#387dd2b3dcbb3380ad35b8efa54624564ecfd759";
      hash = "sha256-sDR0L5Jdgh/AbzrepuWtXTobhqGr9HIO0RyErUIOR/w=";
      rev = "387dd2b3dcbb3380ad35b8efa54624564ecfd759";
    };
  }
  {
    name = "extism-1.0.0-rc2-V9UAzgaeHABw5u7B9ooEopLioGovN5xsM97aaMydd3Hi";
    path = fetchZigArtifact {
      name = "extism";
      url = "git+https://github.com/Cethannel/zig-sdk.git#3d8c8026d4d8e82458ad80437d62a57014f72d1f";
      hash = "sha256-pp7booxMNsnZV/8pVAMs1npSieF6u4PFmPZ8Jrn0TYg=";
      rev = "3d8c8026d4d8e82458ad80437d62a57014f72d1f";
    };
  }
  {
    name = "zclay-0.0.0-Ej1rkMHHAABluPgeTKZu3gBCSkDfD1NYXsUbEvJZ6kYL";
    path = fetchZigArtifact {
      name = "zclay";
      url = "git+https://github.com/johan0A/clay-zig-bindings.git#c439f254d974d4235be27157e530836e854d312c";
      hash = "sha256-yvet9NiUe74OREhBXSLMaRp+F75SSN7bpIBED+tZC6M=";
      rev = "c439f254d974d4235be27157e530836e854d312c";
    };
  }
  {
    name = "N-V-__8AAO23UQAhH_BQUUOoxHaKW4XAbiVmGlGJO2sApBST";
    path = fetchZigArtifact {
      name = "clay";
      url = "git+https://github.com/nicbarker/clay?ref=v0.13#6d23a35d1596f139998b2994a63a1d5a982e713b";
      hash = "sha256-ul5ozeNwRtWk7MRVdOHhZ9fFPEBoTJkqLRpt7K/RDEk=";
      rev = "6d23a35d1596f139998b2994a63a1d5a982e713b";
    };
  }
  {
    name = "uuid-0.3.0-oOieIYF1AAA_BtE7FvVqqTn5uEYTvvz7ycuVnalCOf8C";
    path = fetchZigArtifact {
      name = "uuid";
      url = "https://github.com/r4gus/uuid-zig/archive/refs/tags/0.3.1.tar.gz";
      hash = "sha256-cDxgHeHaD9d1B/YLh7iPAkSwQgGq/AyHhyR/c/cqxQc=";
    };
  }
  {
    name = "ziglangSet-0.0.1-VUjv0poUAgCNnJ8mjuXpZ81KSDap5Nmd_WLb7hFRS18f";
    path = fetchZigArtifact {
      name = "ziglangSet";
      url = "git+https://github.com/deckarep/ziglang-set.git#1907fc6cd76caace357091f6e229cb417677b522";
      hash = "sha256-qVGuj6CDl6/xbyEGWO/4YZL5sYpaesxw9V+i3ya7JG8=";
      rev = "1907fc6cd76caace357091f6e229cb417677b522";
    };
  }
]
